//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore_65131483.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc.Html;

    public partial class CHITIETDONHANG
    {
        public int MaCTDH { get; set; }
        public int MaDH { get; set; }
        public int MaSach { get; set; }
        public int SoLuong { get; set; }
        public decimal DonGia { get; set; }
    
        public virtual DONHANG DONHANG { get; set; }
        public virtual SACH SACH { get; set; }

        public CHITIETDONHANG ( int maDH, int maSach, int soLuong, decimal donGia)
        {
           
            MaDH = maDH;
            MaSach = maSach;
            SoLuong = soLuong;
            DonGia = donGia;
         
        }
        public CHITIETDONHANG () { }
    }
}
