//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore_65131483.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHGIA
    {
        public int MaDG { get; set; }
        public int MaTK { get; set; }
        public int MaSach { get; set; }
        public byte Diem { get; set; }
        public string BinhLuan { get; set; }
        public Nullable<System.DateTime> NgayDanhGia { get; set; }
        public int MaDH { get; set; }
    
        public virtual SACH SACH { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
        public virtual DONHANG DONHANG { get; set; }
    }
}
